### ISSUE TITLE
Syntax consistency

### ISSUE THREAD

**Issue by haydnba** [fac-14/team4week1#14]
https://github.com/fac-14/team4week1/blob/3920c440a6050131acd950fac99ac6ea9a7db005/index.html#L21-L24

(there are a few other instances of this in your codebase)

Try to make sure to keep consistent with your syntax - especially with quotation marks. The convention is to always use double quotes in html files. See google style guide e.g. https://google.github.io/styleguide/htmlcssguide.html#HTML_Quotation_Marks

**Comment by dupreesi** [comment]
thank you, done :)
