### ISSUE TITLE
HTML syntax / style

### ISSUE THREAD

**Issue by arrested-developer** [fac-14/team4week1#24]
* Your code is mostly indented nicely to show the heirarchy 😸, but in a couple of places it needs fixing.

* You should remove gaps between html attributes and values, i.e.

```html
<img src="image/js.png" alt ="javascript">
```

* You should be consistent about using either double or single quotes in your html. AFAIK both are acceptable but double quotes seem to be the general standard 🤓

**Comment by arrested-developer** [comment]
Your CSS also has inconsistent style, you could agree how much to indent your lines by

**Comment by dupreesi** [comment]
thank you!
