### ISSUE TITLE
All-caps text in heading might cause accessibility issues

### ISSUE THREAD

**Issue by VirtualDOMinic** [fac-14/team4week1#30]
Nice use of colours and shadow to make the text over the image clearly visible! :+1: 

I've heard that words written in uppercase can be harder for some dyslexics to understand, as they're not used to reading words formatted in that way. You may want to use sentence case instead :).

**Comment by Brymon** [comment]
Very consistent color palet, makes it very easy to real all text and focuses the attention on important elements! Well done all!
